version: "3.9"

networks:
  local-dynamo-network:

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: any-dummy-aws-access-key-id
      AWS_SECRET_ACCESS_KEY: any-dummy-aws-secret-access-key
    networks:
      - local-dynamo-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M  