version: "3.9"

networks:
  local-dynamo-network:

services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "800:8000"

    networks:
      - local-dynamo-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M  