version: "3.9"
services: 
    mysql:
        image: mysql
        ports:
            - "3306:3306"
        deploy:
            resources:
                limits:
                    memory: 250M
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "dev_db"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: 'adminpassword'
        networks: 
            - mysqlnet
    
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        depends_on: 
            - mysql
        networks: 
            - mysqlnet

networks: 
    mysqlnet: