version: "3.9"
networks:
  mass-transit-network:

services:
  rabbit-mq:
    image: "bitnami/rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment: 
       RABBITMQ_USERNAME: admin
       RABBITMQ_PASSWORD: admin
       RABBITMQ_PLUGINS: rabbitmq_management
    networks:
    - mass-transit-network
    deploy:
      resources:
        limits:
            memory: 450M