version: "3.8"
services: 
    db:
        image: "mysql"
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        networks:
            - api-curso-udemy
        ports:
            - "3306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rest_read_udemy
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        deploy:
            resources:
                limits:
                    memory: 300M
                    cpus: 0.5
                    
    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
        networks:   
        - api-curso-udemy
        depends_on: 
            - db

networks:
    api-curso-udemy: